import {getChatGPTUser} from '../../chatgpt-auth';
import {db,workspace} from '@/lib/db';
import {reportSchema,sanitize} from '@/lib/reports';
import {z} from 'zod';
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to access your workspace'},401);try{return reply(await workspace(user.userId));}catch{return reply({error:'Workspace storage is unavailable. Please try again.'},503);}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to save changes'},401);const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return reply({error:'Invalid request origin'},403);if(!request.headers.get('content-type')?.includes('application/json'))return reply({error:'Expected JSON'},415);
try{const reader=request.body?.getReader();const chunks:Uint8Array[]=[];let size=0;if(reader){while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>1048576){await reader.cancel();return reply({error:'Report exceeds the 1 MiB limit'},413);}chunks.push(value);}}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}const raw=new TextDecoder().decode(bytes);const body=JSON.parse(raw);const owner=user.userId;
if(body.action==='project'){const v=z.object({name:z.string().trim().min(1).max(80),repository:z.string().url().max(250).refine(s=>/^https:\/\/github\.com\/[\w.-]+\/[\w.-]+\/?$/.test(s),'Use a GitHub repository URL')}).parse(body);const id=crypto.randomUUID();await db().prepare('INSERT INTO projects (id,owner,name,repository,created_at) VALUES (?,?,?,?,?)').bind(id,owner,v.name,v.repository,new Date().toISOString()).run();return reply({id},201);}
if(body.action==='import'){const v=z.object({projectId:z.string().uuid(),label:z.string().trim().min(1).max(120),report:reportSchema}).parse(body);const project=await db().prepare('SELECT id FROM projects WHERE id = ? AND owner = ?').bind(v.projectId,owner).first();if(!project)return reply({error:'Project not found'},404);const id=crypto.randomUUID();await db().prepare('INSERT INTO runs (id,owner,project_id,label,report,created_at) VALUES (?,?,?,?,?,?)').bind(id,owner,v.projectId,v.label,JSON.stringify(sanitize(v.report)),new Date().toISOString()).run();return reply({id},201);}
if(body.action==='baseline'){const {runId}=z.object({runId:z.string().uuid()}).parse(body);const run:any=await db().prepare('SELECT project_id,report FROM runs WHERE id = ? AND owner = ?').bind(runId,owner).first();if(!run)return reply({error:'Run not found'},404);if(!JSON.parse(run.report).ok)return reply({error:'A baseline must be a passing run'},400);await db().prepare('UPDATE projects SET baseline_id = ? WHERE id = ? AND owner = ?').bind(runId,run.project_id,owner).run();return reply({ok:true});}
return reply({error:'Unknown action'},400);
}catch(error){if(error instanceof z.ZodError)return reply({error:error.issues.map(i=>i.message).slice(0,3).join('; ')},400);if(error instanceof SyntaxError)return reply({error:'Invalid JSON'},400);console.error('Workspace write failed',error);return reply({error:'Could not save. Your input has been preserved.'},503);}}
