'use client';
import {useEffect,useMemo,useState} from 'react';
import {usePathname,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {LayoutDashboard,FolderGit2,Activity,ListChecks,Layers,Plug,Settings,ArrowUpRight,ArrowLeft,ArrowRight,Plus,Upload,Search,GitBranch,CheckCircle2,XCircle,AlertTriangle,Download,Copy,BookOpen,ShieldCheck,Loader2,Check,FileJson} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {toast} from 'sonner';
import {example,nav,type Workspace,type Run,type Scenario} from '@/lib/data';
const icons=[LayoutDashboard,FolderGit2,Activity,ListChecks,Layers,Plug,Settings];
function Status({status}:{status:string}){const good=status==='PASS';const Icon=good?CheckCircle2:status==='FAIL'?XCircle:AlertTriangle;return <span className={'status '+(good?'good':status==='FAIL'?'bad':'warn')}><Icon size={14}/>{status}</span>}
function date(value:string){return new Date(value).toLocaleString('en-US',{timeZone:'UTC',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})+' UTC';}
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Blank({title,body,image,action}:{title:string;body:string;image?:string;action?:React.ReactNode}){return <Empty className="empty-state"><EmptyHeader>{image&&<img src={'/assets/'+image+'.webp'} alt=""/>}<EmptyTitle>{title}</EmptyTitle><EmptyDescription>{body}</EmptyDescription></EmptyHeader>{action}</Empty>}
export default function Dashboard({user}:{user:{name:string;email:string}|null}){
 const path=usePathname()??'/app';const search=useSearchParams();const demo=search.get('demo')==='1'||!user;const suffix=demo?'?demo=1':'';
 const section=path.split('/')[2]??'';const runId=path.split('/')[3];const [data,setData]=useState<Workspace>({projects:[],runs:[]});const [loading,setLoading]=useState(!demo);const [error,setError]=useState('');const [query,setQuery]=useState('');const[filter,setFilter]=useState('all');const[project,setProject]=useState('all');const[dialog,setDialog]=useState<'project'|'import'|null>(null);const[busy,setBusy]=useState(false);const[formError,setFormError]=useState('');const[name,setName]=useState('');const[repo,setRepo]=useState('');const[label,setLabel]=useState('');const[importProject,setImportProject]=useState('');const[file,setFile]=useState<File|null>(null);const[detail,setDetail]=useState<{run:Run;scenario:Scenario}|null>(null);
 const active=demo?example:data;
 async function refresh(){setLoading(true);setError('');try{const r=await fetch('/api/workspace');const v=await r.json() as Workspace & {error?:string};if(!r.ok)throw Error(v.error||'Request failed');setData(v);}catch(e){setError(e instanceof Error?e.message:'Could not load workspace');}finally{setLoading(false);}}
 useEffect(()=>{if(!demo)void refresh();else setLoading(false);},[demo]);
 useEffect(()=>{setQuery('');setFilter('all');setDetail(null)},[path]);
 const selectedRuns=active.runs.filter(r=>project==='all'||r.projectId===project);
 const filtered=selectedRuns.filter(r=>(filter==='all'||(r.report.ok?'PASS':'FAIL')===filter)&&`${r.label} ${r.report.revision??''} ${r.id}`.toLowerCase().includes(query.toLowerCase()));
 const scenarios=useMemo(()=>{const seen=new Set<string>();return selectedRuns.flatMap(run=>run.report.scenarios.filter(s=>{const key=run.projectId+s.id;if(seen.has(key))return false;seen.add(key);return true;}).map(scenario=>({run,scenario})));},[active,project]);
 const matchingScenarios=scenarios.filter(({scenario:s})=>s.id.toLowerCase().includes(query.toLowerCase()));
 const current=active.runs.find(r=>r.id===runId);const passing=selectedRuns.filter(r=>r.report.ok).length;const failures=selectedRuns.reduce((n,r)=>n+r.report.scenarios.filter(s=>s.status!=='PASS').length,0);
 const projectName=(id:string)=>active.projects.find(p=>p.id===id)?.name??'Unknown project';
 const openDialog=(value:'project'|'import')=>{if(demo){toast.info(user?'Switch to your workspace to save projects and reports.':'Sign in to save projects and reports.');return;}setFormError('');setDialog(value);setImportProject(project!=='all'?project:active.projects[0]?.id??'');};
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setFormError('');try{let payload:any;if(dialog==='project')payload={action:'project',name,repository:repo};else{if(!file)throw Error('Choose a report JSON file');if(file.size>1048576)throw Error('Reports must be smaller than 1 MiB');payload={action:'import',projectId:importProject,label:label||file.name,report:JSON.parse(await file.text())};}const res=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await res.json() as {error?:string};if(!res.ok)throw Error(result.error||'Request failed');setDialog(null);setName('');setRepo('');setLabel('');setFile(null);await refresh();toast.success(payload.action==='project'?'Project created':'Report imported');}catch(e){setFormError(e instanceof Error?e.message:'Could not save');}finally{setBusy(false);}}
 async function baseline(run:Run){if(demo){toast.info('Baseline changes are available in your saved workspace.');return;}setBusy(true);try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'baseline',runId:run.id})});const v=await r.json() as {error?:string};if(!r.ok)throw Error(v.error||'Request failed');await refresh();toast.success('Passing baseline selected');}catch(e){toast.error(e instanceof Error?e.message:'Could not set baseline');}finally{setBusy(false);}}
 const importButton=<Button onClick={()=>openDialog(active.projects.length?'import':'project')}><Upload size={15}/>{active.projects.length?'Import report':'Create project'}</Button>;
 const runTable=(runs:Run[])=><div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Status</TableHead><TableHead>Run</TableHead><TableHead>Project</TableHead><TableHead>Revision</TableHead><TableHead>Scenarios</TableHead><TableHead>Imported</TableHead><TableHead><span className="sr-only">Open</span></TableHead></TableRow></TableHeader><TableBody>{runs.map(run=><TableRow key={run.id}><TableCell><Status status={run.report.ok?'PASS':'FAIL'}/></TableCell><TableCell><Link className="run-link" href={'/app/runs/'+run.id+suffix}>{run.label}</Link>{active.projects.find(p=>p.baselineId===run.id)&&<span className="baseline-label">BASELINE</span>}</TableCell><TableCell>{projectName(run.projectId)}</TableCell><TableCell><span className="revision"><GitBranch size={12}/>{run.report.revision?.slice(0,7)??'unknown'}</span></TableCell><TableCell>{run.report.scenarios.filter(s=>s.status==='PASS').length} / {run.report.scenarios.length}</TableCell><TableCell className="muted nowrap">{date(run.createdAt)}</TableCell><TableCell><Link href={'/app/runs/'+run.id+suffix} aria-label={'Open '+run.label}><ArrowUpRight size={16}/></Link></TableCell></TableRow>)}</TableBody></Table></div>;
 const heading=(title:string,subtitle:string,action?:React.ReactNode)=><div className="page-heading"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>;
 return <SidebarProvider defaultOpen style={{'--sidebar-width':'232px'} as React.CSSProperties}><Sidebar className="app-sidebar"><SidebarHeader><Link className="brand" href="/"><img src="/assets/aurat-mark.webp" alt=""/>aurat.</Link><div className="workspace-label"><span className="workspace-avatar">A</span><div><strong>{demo?'Proof workspace':'Your workspace'}</strong><small>{demo?'Scout · example reports':'Developer preview'}</small></div></div></SidebarHeader><SidebarContent><SidebarMenu>{nav.map(([url,title],i)=>{const Icon=icons[i];return <SidebarMenuItem key={url}><SidebarMenuButton asChild isActive={section===url}><Link href={'/app'+(url?'/'+url:'')+suffix}><Icon size={17}/><span>{title}</span></Link></SidebarMenuButton></SidebarMenuItem>})}</SidebarMenu><div className="sidebar-note"><ShieldCheck size={18}/><p>Your runs.<br/>Your evidence.</p><small>Reports are imported from your own CLI or CI.</small></div></SidebarContent><SidebarFooter><Link href="/docs" className="sidebar-doc"><BookOpen size={16}/>Documentation<ArrowUpRight size={14}/></Link><div className="user-block"><span>{user?.name?.[0]?.toUpperCase()??'D'}</span><div><strong>{user?.name??'Demo visitor'}</strong><small>{user?'Private workspace':'Read-only example'}</small></div></div></SidebarFooter></Sidebar><SidebarInset className="app-inset"><header className="app-topbar"><div><SidebarTrigger/><span className="muted">Workspace</span><span className="breadcrumb-slash">/</span><span>{nav.find(n=>n[0]===section)?.[1]??'Overview'}</span></div><div><Select value={project} onValueChange={setProject}><SelectTrigger className="project-select" aria-label="Filter project"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All projects</SelectItem>{active.projects.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select><Link href="/docs" className="top-doc"><BookOpen size={16}/></Link></div></header>
 {demo&&<div className="demo-banner"><span><span className="demo-pill">EXAMPLE DATA</span> Real Scout reproduction. Changes here are read-only.</span>{user?<Link href={'/app'+(section?'/'+section:'')}>Your workspace <ArrowRight size={14}/></Link>:<a href="/signin-with-chatgpt?return_to=%2Fapp" target="_top">Sign in to connect <ArrowRight size={14}/></a>}</div>}
 <div className="dashboard-content">{loading?<div className="loading-state"><Loader2 className="spin"/>Loading your workspace…</div>:error?<Blank title="Workspace unavailable" body={error} action={<Button onClick={refresh}>Try again</Button>}/>:<>
 {section===''&&<>{heading('Overview','A clear view of the behavior you depend on.',importButton)}<div className="stat-grid">{[['Total runs',selectedRuns.length,'Imported reports'],['Passing runs',passing,selectedRuns.length?Math.round(passing/selectedRuns.length*100)+'% of runs':'No runs yet'],['Failed scenarios',failures,'Across imported runs'],['Projects',active.projects.length,'Connected by report import']].map(([title,value,sub])=><div className="stat" key={title}><span>{title}</span><strong>{value}</strong><small>{sub}</small></div>)}</div>{selectedRuns.length?<><div className="panel-heading"><h2>Recent runs</h2><Link href={'/app/runs'+suffix}>View all <ArrowRight size={14}/></Link></div>{runTable(selectedRuns.slice(0,6))}<div className="overview-bottom"><div className="insight-panel"><span className="eyebrow">LATEST EVIDENCE</span><h3>{selectedRuns[0].report.ok?'The latest run passed.':'A workflow needs attention.'}</h3><p>{selectedRuns[0].report.scenarios.length} scenarios checked in {projectName(selectedRuns[0].projectId)}. Open the run to inspect assertion results and coverage.</p><Link className="text-link" href={'/app/runs/'+selectedRuns[0].id+suffix}>Inspect latest run <ArrowRight size={15}/></Link></div><div className="setup-panel"><Plug size={22}/><h3>Bring your own workflow.</h3><p>Connect a repository, then import a report produced by Aurat.</p><Link className="text-link" href={'/app/connections'+suffix}>Set up a connection <ArrowRight size={15}/></Link></div></div></>:<Blank title="Your first run starts in your codebase." body="Create a project, run Aurat locally or in CI, then import the report here." image="empty-runs" action={importButton}/>}</>}
 {section==='projects'&&<>{heading('Projects','Organize regression evidence around your repositories.',<Button onClick={()=>openDialog('project')}><Plus size={16}/>New project</Button>)}{active.projects.length?<div className="project-grid">{active.projects.map(p=>{const runs=active.runs.filter(r=>r.projectId===p.id);return <div className="project-card" key={p.id}><div className="project-card-top"><FolderGit2 size={24}/><span className="tag">REPORT IMPORTS</span></div><h2>{p.name}</h2><a href={p.repository} target="_blank" rel="noreferrer">{p.repository.replace('https://github.com/','')} <ArrowUpRight size={13}/></a><div className="project-stats"><span>{runs.length} runs</span><span>{p.baselineId?'Baseline selected':'No baseline yet'}</span></div><div className="project-card-bottom">{runs[0]?<Status status={runs[0].report.ok?'PASS':'FAIL'}/>:<span className="muted">Awaiting first report</span>}<Button variant="ghost" onClick={()=>{setProject(p.id);toast.success(p.name+' selected in project filter')}}>Select <ArrowRight size={14}/></Button></div></div>})}</div>:<Blank title="Connect your first project" body="Start with the repository containing the workflow you want to protect." image="connection-bridge" action={<Button onClick={()=>openDialog('project')}>New project</Button>}/>}</>}
 {section==='runs'&&!runId&&<>{heading('Runs','Your latest 100 reports, with the evidence behind each result.',importButton)}<div className="table-controls"><div className="search-field"><Search size={16}/><Input placeholder="Search run or revision…" aria-label="Search runs" value={query} onChange={e=>setQuery(e.target.value)}/></div><Select value={filter} onValueChange={setFilter}><SelectTrigger className="status-select" aria-label="Filter status"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="PASS">Passing</SelectItem><SelectItem value="FAIL">Failed / incomplete</SelectItem></SelectContent></Select><span className="muted">{filtered.length} runs</span></div>{filtered.length?runTable(filtered):<Blank title={selectedRuns.length?'No matching runs':'No runs yet'} body={selectedRuns.length?'Try a different search or status filter.':'Import a report to see scenario results and coverage.'} image={selectedRuns.length?undefined:'empty-runs'} action={selectedRuns.length?<Button variant="outline" onClick={()=>{setQuery('');setFilter('all')}}>Clear filters</Button>:importButton}/>}</>}
 {section==='runs'&&runId&&(current?<><Link className="back-link" href={'/app/runs'+suffix}><ArrowLeft size={14}/>All runs</Link>{heading(current.label,projectName(current.projectId)+' · '+date(current.createdAt),<div className="heading-actions"><Button variant="outline" onClick={()=>download(current.report,current.id+'.json')}><Download size={15}/>JSON</Button><Button disabled={!current.report.ok||busy||demo} onClick={()=>baseline(current)}>Set as baseline</Button></div>)}<div className="run-metadata"><Status status={current.report.ok?'PASS':'FAIL'}/><span className="revision"><GitBranch size={14}/>{current.report.revision??'unknown revision'}</span><span>{current.report.lane}</span><span>{current.report.scenarios.reduce((n,s)=>n+s.durationMs,0)}ms total scenario time</span></div><div className="panel-heading"><h2>Scenario results</h2><span className="muted">Click a scenario for evidence</span></div><div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Status</TableHead><TableHead>Scenario</TableHead><TableHead>Model coverage</TableHead><TableHead>Tools</TableHead><TableHead>Duration</TableHead><TableHead>vs baseline</TableHead></TableRow></TableHeader><TableBody>{current.report.scenarios.map(s=>{const baselineId=active.projects.find(p=>p.id===current.projectId)?.baselineId;const b=active.runs.find(r=>r.id===baselineId)?.report.scenarios.find(x=>x.id===s.id);return <TableRow key={s.id}><TableCell><Status status={s.status}/></TableCell><TableCell><button className="run-link" onClick={()=>setDetail({run:current,scenario:s})}>{s.id}</button></TableCell><TableCell>{s.coverage?`${s.coverage.model.consumed} / ${s.coverage.model.total}`:'—'}</TableCell><TableCell>{s.coverage?`${s.coverage.tools.consumed} / ${s.coverage.tools.total}`:'—'}</TableCell><TableCell>{s.durationMs}ms</TableCell><TableCell>{!b?'No baseline':b.status===s.status?'Unchanged':s.status==='PASS'?'Improved':'Changed'}</TableCell></TableRow>})}</TableBody></Table></div><div className="boundary-note"><ShieldCheck size={18}/><p>Coverage proves recorded interactions were consumed. Node HTTP interception is not an OS sandbox; unwrapped side effects are outside its boundary.</p></div></>:<Blank title="Run not found" body="This run may not belong to your workspace." action={<Link className="button" href={'/app/runs'+suffix}>View runs</Link>}/>)}
 {section==='scenarios'&&<>{heading('Scenarios','The latest recorded result for each scenario in a project.')}<div className="table-controls"><div className="search-field"><Search size={16}/><Input placeholder="Find a scenario…" aria-label="Search scenarios" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{matchingScenarios.length?<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Status</TableHead><TableHead>Scenario</TableHead><TableHead>Project</TableHead><TableHead>Failures</TableHead><TableHead>Latest run</TableHead></TableRow></TableHeader><TableBody>{matchingScenarios.map(({run,scenario:s})=><TableRow key={run.projectId+s.id}><TableCell><Status status={s.status}/></TableCell><TableCell><button className="run-link" onClick={()=>setDetail({run,scenario:s})}>{s.id}</button></TableCell><TableCell>{projectName(run.projectId)}</TableCell><TableCell>{s.failures.length}</TableCell><TableCell><Link href={'/app/runs/'+run.id+suffix}>{run.report.revision?.slice(0,7)??'Open run'} ↗</Link></TableCell></TableRow>)}</TableBody></Table></div>:<Blank title={query?"No matching scenarios":"No scenarios to inspect"} body={query?"Try another search.":"Scenario results appear when you import your first report."} image={query?undefined:"empty-runs"} action={query?<Button variant="outline" onClick={()=>setQuery('')}>Clear search</Button>:importButton}/>}</>}
 {section==='fixtures'&&<>{heading('Fixture coverage','See whether recorded interactions were consumed.')}<div className="info-banner"><Layers size={18}/><p>Raw fixtures stay in your repository. This view shows coverage from imported reports, not a copy of model prompts or tool credentials.</p></div>{scenarios.length?<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Scenario</TableHead><TableHead>Model interactions</TableHead><TableHead>Tool interactions</TableHead><TableHead>HTTP guard</TableHead><TableHead>Pending</TableHead></TableRow></TableHeader><TableBody>{scenarios.map(({run,scenario:s})=><TableRow key={run.projectId+s.id}><TableCell><button className="run-link" onClick={()=>setDetail({run,scenario:s})}>{s.id}</button></TableCell><TableCell>{s.coverage?`${s.coverage.model.consumed}/${s.coverage.model.total}`:'Not reported'}</TableCell><TableCell>{s.coverage?`${s.coverage.tools.consumed}/${s.coverage.tools.total}`:'Not reported'}</TableCell><TableCell>{s.coverage?.httpGuard?'Active':'Not confirmed'}</TableCell><TableCell>{s.coverage?s.coverage.model.pending.length:'—'}</TableCell></TableRow>)}</TableBody></Table></div>:<Blank title="No fixture coverage yet" body="Import a run to inspect model and tool consumption." image="empty-fixtures" action={importButton}/>}</>}
 {section==='connections'&&<>{heading('Connections','Bring your repository and regression reports together.')}<div className="connection-layout"><div className="connection-main"><div className="connection-heading"><FolderGit2 size={28}/><div><h2>GitHub repository</h2><p>Project context, with report imports.</p></div><span className="tag">AVAILABLE</span></div><ol className="setup-steps"><li><span>1</span><div><h3>Create a project</h3><p>Add a name and repository URL. No repository token required.</p><Button variant="outline" onClick={()=>openDialog('project')}><Plus size={15}/>New project</Button></div></li><li><span>2</span><div><h3>Produce a report in CI</h3><p>Run your suite and upload the JSON as a GitHub Actions artifact.</p><pre>{'npx aurat test --suite .aurat/suite.json \\\n  --report .aurat/report.json'}</pre><Button variant="ghost" onClick={async()=>{try{await navigator.clipboard.writeText('- name: Upload Aurat report\n  uses: actions/upload-artifact@v4\n  if: always()\n  with:\n    name: aurat-report\n    path: .aurat/report.json\n    include-hidden-files: true');toast.success('Artifact workflow copied')}catch{toast.error('Clipboard unavailable')}}}><Copy size={14}/>Copy artifact workflow</Button></div></li><li><span>3</span><div><h3>Import and inspect</h3><p>Download your CI artifact and import its JSON report. Stored under your signed-in account.</p>{importButton}</div></li></ol></div><aside className="connection-aside"><img src="/assets/connection-bridge.webp" alt="Pearl connection bridge"/><h3>A deliberate first connection.</h3><p>This preview supports real report imports. Automatic GitHub synchronization and remote execution are not enabled.</p><Link className="text-link" href="/docs#doc-2">Connection guide <ArrowUpRight size={15}/></Link></aside></div></>}
 {section==='settings'&&<>{heading('Settings','Workspace identity and report data.')}<div className="settings-panel"><h2>Workspace</h2><div className="setting-row"><div><strong>Signed-in account</strong><p>{user?.email??'Example workspace · sign in to save your own data'}</p></div><span className="tag">{user?'PRIVATE':'DEMO'}</span></div><div className="setting-row"><div><strong>Export workspace data</strong><p>Download your projects and imported reports as JSON.</p></div><Button variant="outline" onClick={()=>download(active,'aurat-workspace.json')}><Download size={15}/>Export</Button></div><div className="setting-row"><div><strong>Data handling</strong><p>Review reports for sensitive business data before importing. Automated redaction is a baseline, not complete PII protection.</p></div><ShieldCheck size={22}/></div><div className="setting-row"><div><strong>Deployment scope</strong><p>Private developer preview. Team access, billing and automatic CI ingestion are not enabled.</p></div></div></div>{user&&<a className="text-link" href="/signout-with-chatgpt?return_to=%2F" target="_top">Sign out →</a>}</>}
 </>}</div></SidebarInset>
 <Dialog open={!!dialog} onOpenChange={open=>{if(!busy&&!open)setDialog(null)}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{dialog==='project'?'Create a project':'Import a report'}</DialogTitle><DialogDescription>{dialog==='project'?'Connect the repository containing your regression scenarios.':'Select a project and a sanitized Aurat v1 JSON report, up to 1 MiB.'}</DialogDescription></DialogHeader><form onSubmit={submit}>{dialog==='project'?<><Label htmlFor="name">Project name</Label><Input id="name" required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Customer support agent"/><Label htmlFor="repository">GitHub repository</Label><Input id="repository" type="url" required value={repo} onChange={e=>setRepo(e.target.value)} placeholder="https://github.com/your-team/agent"/></>:<><Label>Project</Label><Select value={importProject} onValueChange={setImportProject}><SelectTrigger aria-label="Import project"><SelectValue placeholder="Select project"/></SelectTrigger><SelectContent>{active.projects.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select><Label htmlFor="runlabel">Run name</Label><Input id="runlabel" value={label} onChange={e=>setLabel(e.target.value)} placeholder="Agent routing · pull request 42" maxLength={120}/><Label htmlFor="report">Report JSON</Label><Input id="report" type="file" accept=".json,application/json" required onChange={e=>setFile(e.target.files?.[0]??null)}/></>}{formError&&<p role="alert" className="form-error">{formError}</p>}<Button type="submit" disabled={busy||dialog==='import'&&!importProject}>{busy?<Loader2 className="spin" size={16}/>:dialog==='project'?<Plus size={16}/>:<Upload size={16}/>} {dialog==='project'?'Create project':'Import report'}</Button></form></DialogContent></Dialog>
 <Sheet open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><SheetContent className="evidence-sheet">{detail&&<><SheetHeader><span className="eyebrow">SCENARIO EVIDENCE</span><SheetTitle>{detail.scenario.id}</SheetTitle><SheetDescription>{detail.run.label}</SheetDescription></SheetHeader><div className="sheet-body"><Status status={detail.scenario.status}/><Tabs defaultValue="assertions"><TabsList><TabsTrigger value="assertions">Assertions</TabsTrigger><TabsTrigger value="events">Events</TabsTrigger><TabsTrigger value="logs">Logs</TabsTrigger></TabsList><TabsContent value="assertions">{detail.scenario.failures.length?detail.scenario.failures.map((f,i)=><div className="assertion-failure" key={i}><span><XCircle size={16}/>{f.field}</span><p>{f.message}</p></div>):<div className="assertion-pass"><CheckCircle2/>All configured assertions passed.</div>}<h3>Fixture coverage</h3><pre>{JSON.stringify(detail.scenario.coverage??{message:'Coverage not reported'},null,2)}</pre></TabsContent><TabsContent value="events">{detail.scenario.events?.length?detail.scenario.events.map((e,i)=><div className="event-row" key={i}><span className="mini-label">{String(i+1).padStart(2,'0')} / {String(e.type)}</span><pre>{JSON.stringify(e,null,2)}</pre></div>):<p>No events in this report.</p>}</TabsContent><TabsContent value="logs"><h3>Standard output</h3><pre>{detail.scenario.process?.stdout||'No output included.'}</pre><h3>Standard error</h3><pre>{detail.scenario.process?.stderr||'No error log included.'}</pre></TabsContent></Tabs><Link className="text-link" href={'/app/runs/'+detail.run.id+suffix} onClick={()=>setDetail(null)}>Open source run <ArrowUpRight size={15}/></Link></div></>}</SheetContent></Sheet>
 </SidebarProvider>
}
