'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Check,Copy,GitBranch,Terminal,Menu,X,ChevronRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {toast} from 'sonner';
import {MotionToggle} from '@/components/motion';
export function Brand(){return <Link href="/" className="brand" aria-label="Aurat home"><img src="/assets/aurat-mark.webp" alt=""/>aurat<span className="brand-period">.</span></Link>}
export default function Landing(){const[menu,setMenu]=useState(false);const steps=[['capture','Record the behavior','Save model responses and wrapped tool results from a controlled workflow.','record-cassette'],['replay','Run the changed code','Replay external interactions while your actual application logic executes.','replay-loop'],['verify','Check what matters','Assert the action, arguments, order and final outcome. Incomplete runs fail.','verify-gate']];return <main className="marketing"><div className="page-rails" aria-hidden="true"><i/><i/></div><header className="site-nav wrap"><Brand/><nav className={menu?'open':''}><a href="#workflow">How it works</a><a href="#evidence">The proof</a><Link href="/docs">Documentation</Link><a href="https://github.com/8dazo/aurat" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a></nav><Link className="button small" href="/app">Open workspace <ArrowUpRight size={15}/></Link><MotionToggle/><button className="mobile-menu" aria-expanded={menu} aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<section className="hero wrap"><div className="hero-copy"><a className="eyebrow release" href="https://github.com/8dazo/aurat">DEVELOPER PREVIEW <span>0.2</span><ChevronRight size={14}/></a><h1>Replay the run.<br/><span>Catch the regression.</span></h1><p>Your agent changed.<br/>Know exactly what broke before you merge.</p><div className="hero-actions"><Link className="button" href="/app?demo=1">Explore the workspace <ArrowUpRight size={17}/></Link><Link href="/docs" className="text-link">Start with the CLI <ArrowRight size={16}/></Link></div><div className="hero-notes"><span>Node.js 22+</span><span>Local replay</span><span>Your existing stack</span></div></div><div className="hero-art" data-motion-art><div className="orbital-guide" aria-hidden="true"><i/><i/><i/></div><img src="/assets/hero-replay.webp?v=2" alt="Pearlescent sculptural path folding back into a replay loop" fetchPriority="high"/><span className="art-caption mono">01 — BEHAVIOR, REPEATED.</span></div></section>
<div className="wrap product-window" data-reveal><div className="window-signal" aria-hidden="true"/><div className="window-bar"><Brand/><span>Scout / Narration validation</span><span className="window-caption">ACTUAL REGRESSION PROOF</span></div><div className="proof-layout"><aside><span className="mini-label">SCENARIOS</span>{['valid-narration','reject-numeric-summary','reject-object-action','reject-nonstring-reasons'].map((n,i)=><div key={n} className={i===1?'active':''}><span className={i?'status-dot fail':'status-dot pass'}/>{n}</div>)}</aside><div className="proof-main"><div className="split-title"><div><span className="tag peach">REGRESSION CAUGHT</span><h3>A number is not a summary.</h3></div><GitBranch size={20}/></div><p>The model returned <code>summary: 42</code>. Scout accepted it.<br/>Aurat caught the invalid outcome.</p><div className="comparison"><div><small>EXPECTED</small><pre>{'{ "rejected": true }'}</pre></div><div><small>ACTUAL · ORIGINAL SOURCE</small><pre className="peach-text">{'{ "rejected": false }'}</pre></div></div><div className="proof-bottom"><span><Check size={15}/> Same fixtures after the fix: 4 / 4 pass</span><Link href="/app/runs/scout-original?demo=1">Inspect the run <ArrowRight size={15}/></Link></div></div></div></div>
<section className="statement wrap" data-reveal><span className="eyebrow">A PLAUSIBLE ANSWER ISN'T ENOUGH</span><h2>The answer can look right.<br/><span>The workflow can still be wrong.</span></h2><div className="issue-row"><p>A ticket created twice.</p><p>A required step skipped.</p><p>A tool given the wrong argument.</p></div><p className="statement-body">Aurat tests the application around the model. Capture a known workflow, define its expected behavior, and make the next change with evidence.</p></section>
<div className="section-divider wrap" aria-hidden="true"><span>CAPTURE</span><i/><span>REPLAY</span><i/><span>VERIFY</span></div><section id="workflow" className="workflow wrap" data-reveal><div className="section-heading"><div><span className="eyebrow">01 / A TIGHTER FEEDBACK LOOP</span><h2>From a real run<br/>to a reliable test.</h2></div><p>Keep your model SDK and tracing stack.<br/>Add a repeatable check where you ship.</p></div><Tabs defaultValue="capture" orientation="vertical" className="workflow-tabs"><TabsList className="step-list">{steps.map(([id,title,body],i)=><TabsTrigger value={id} key={id} className="step"><span className="step-number">0{i+1}</span><span><strong>{title}</strong><small>{body}</small></span></TabsTrigger>)}</TabsList>{steps.map(([id,title,body,asset],i)=><TabsContent value={id} key={id} className="step-panel" data-motion-art><img src={`/assets/${asset}.webp`} alt={`${title}: original pearl sculpture`} loading="lazy"/><div className="code-pane"><span className="mini-label">{id==='capture'?'CONTROLLED CAPTURE':id==='replay'?'YOUR APPLICATION, EXECUTED':'AN EXPLICIT CONTRACT'}</span><pre>{i===0?'aurat proxy --mode record\n\n// Model traffic + wrapped tools\n// Review fixtures before committing.':i===1?'aurat test --suite .aurat/suite.json\n\nPASS create-ticket-once\nCoverage: model 1/1, tools 1/1':'"expect": {\n  "tools": [{\n    "name": "create_ticket",\n    "count": 1\n  }]\n}'}</pre></div></TabsContent>)}</Tabs></section>
<section id="evidence" className="evidence wrap" data-reveal><div className="section-heading"><div><span className="eyebrow">02 / PROOF OVER PROMISES</span><h2>A real code defect.<br/>Four unchanged fixtures.</h2></div><p>We ran Aurat against Scout's existing narration module. Three malformed responses exposed missing type validation.</p></div><div className="evidence-grid"><div className="evidence-art" data-motion-art><img src="/assets/regression-fracture.webp?v=2" alt="Two pearl paths, one continuous and one interrupted at a fracture" loading="lazy"/></div><div className="evidence-story"><div className="big-metric"><span>1<span>/4</span></span><ArrowRight/><span>4<span>/4</span></span></div><div className="metric-captions"><span>Original source</span><span>After validation fix</span></div><p>Same requests. Same recorded responses. The actual Scout function executes in both cases.</p><a className="text-link" href="https://github.com/8dazo/scout/pull/2">Read the reproduction <ArrowUpRight size={16}/></a><small>Source-discovered defect with synthetic model responses. Not a claimed customer production incident.</small></div></div></section>
<section className="review-section wrap" data-reveal><div className="review-copy"><span className="eyebrow">03 / EVERY FAILURE HAS CONTEXT</span><h2>Know what changed.<br/>And why it matters.</h2><p>Open a run, inspect the failed invariant, and compare it with a passing baseline. Model and tool coverage make missing interactions visible.</p><ul>{['Readable assertion failures','Scenario-level evidence and events','Versioned reports from your own CI'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul><Link className="text-link" href="/app/runs?demo=1">Explore real report data <ArrowRight size={16}/></Link></div><img data-motion-art src="/assets/evidence-stack.webp?v=2" alt="Precisely aligned translucent evidence sheets" loading="lazy"/></section>
<section className="integration wrap" data-reveal><img data-motion-art src="/assets/connection-bridge.webp" alt="Two pearl segments connected into one bridge" loading="lazy"/><div><span className="eyebrow">YOUR CODE. YOUR CI.</span><h2>A small addition<br/>to the way you work.</h2><p>Start locally. Commit your scenarios. Run them in GitHub Actions, then bring the report into your workspace.</p><button className="install-command" onClick={async()=>{try{await navigator.clipboard.writeText('git clone https://github.com/8dazo/aurat.git');toast.success('Clone command copied');}catch{toast.error('Copy unavailable. Select the command manually.')}}}><code>git clone https://github.com/8dazo/aurat</code><Copy size={17}/></button><Link href="/docs" className="text-link">Read the integration guide <ArrowRight size={16}/></Link></div></section>
<section className="closing wrap" data-reveal><img data-motion-art src="/assets/release-orbit.webp?v=2" alt="A precision pearl orbit around a sculptural replay form" loading="lazy"/><div><span className="eyebrow">MAKE THE NEXT CHANGE WITH EVIDENCE</span><h2>Ship the change.<br/>Keep the behavior.</h2><Link className="button" href="/app?demo=1">Explore Aurat <ArrowUpRight size={17}/></Link></div></section>
<footer className="site-footer wrap"><Brand/><p>Deterministic testing for AI agents.</p><Link href="/docs">Docs</Link><a href="https://github.com/8dazo/aurat">GitHub</a><span>Built by Devansh</span></footer></main>}
